//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EToolService.Desktop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EToolService.Desktop.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isključili ste opciju &apos;Aktivan&apos;. Više nećete vidjeti podatke o ovom uposleniku. Jeste li sigurni da želite obrisati uposlenika?.
        /// </summary>
        internal static string delete_warning {
            get {
                return ResourceManager.GetString("delete_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje &apos;Ime&apos; je obavezno..
        /// </summary>
        internal static string employee_name_empty {
            get {
                return ResourceManager.GetString("employee_name_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate odabrati uposlenika koji podnosi zahtjev..
        /// </summary>
        internal static string employee_not_chosen {
            get {
                return ResourceManager.GetString("employee_not_chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje &apos;Pozicija&apos; je obavezno..
        /// </summary>
        internal static string employee_position_empty {
            get {
                return ResourceManager.GetString("employee_position_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje &apos;Plata&apos; je obavezno..
        /// </summary>
        internal static string employee_salary_empty {
            get {
                return ResourceManager.GetString("employee_salary_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje mora biti u brojčanom formatu..
        /// </summary>
        internal static string employee_salary_invalid {
            get {
                return ResourceManager.GetString("employee_salary_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje &apos;Prezime&apos; je obavezno..
        /// </summary>
        internal static string employee_surname_empty {
            get {
                return ResourceManager.GetString("employee_surname_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje je obavezno..
        /// </summary>
        internal static string entry_is_required {
            get {
                return ResourceManager.GetString("entry_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijednost nije validna..
        /// </summary>
        internal static string invalid_value {
            get {
                return ResourceManager.GetString("invalid_value", resourceCulture);
            }
        }
    }
}
